name: Build & Push Prod
on:
  push:
    branches:
        - main
jobs:
  DockerBuildPush:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build api images
      run: |
        cd Web
        docker build -t vatviewer-api -f VatViewer.API/Dockerfile .
        docker build -t vatviewer-jobs-datafeed -f VatViewer.Jobs.Datafeed/Dockerfile .
        docker build -t vatviewer-jobs-database -f VatViewer.Jobs.Database/Dockerfile .
    - name: Tag images
      run: |
        docker tag vatviewer-api ghcr.io/vatviewer/vatviewer-api:latest
        docker tag vatviewer-jobs-datafeed ghcr.io/vatviewer/vatviewer-jobs-datafeed:latest
        docker tag vatviewer-jobs-database ghcr.io/vatviewer/vatviewer-jobs-database:latest
    - name: Push images
      run: |
        docker push ghcr.io/vatviewer/vatviewer-api:latest
        docker push ghcr.io/vatviewer/vatviewer-jobs-datafeed:latest
        docker push ghcr.io/vatviewer/vatviewer-jobs-database:latest