name: Build
on:
  pull_request:
    types: [opened, reopened]
jobs:
  DockerBuildPush:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Build api images
      run: |
        cd Web
        docker build -t vatviewer-api -f VatViewer.API/Dockerfile .
        docker build -t vatviewer-jobs-datafeed -f VatViewer.Jobs.Datafeed/Dockerfile .
        docker build -t vatviewer-jobs-database -f VatViewer.Jobs.Database/Dockerfile .